/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GNApp.controller.GuestBookController', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
        	GuestBookPanel : '#GuestBookPanel',
        	mapArea: '#mapArea'
        	/*
            mainView: '#MainView',
            tweetList: '#TweetList',
            backButton: '#Back',
            tweetPreview: '#TweetPreview'
            */
        	
        },

        control: {
        	"#GuestBookPanel":{
        	  	show : "onShowMap"
        	}
        	/*
            "[action=back]": {
                tap: 'onButtonTap'
            },
            "#TweetList": {
                itemtap: 'onListItemTap'
            }
            */
        }        
    },
    
    onShowMap: function() {
    	console.log("???");
		/* canvas */
		canvas = document.getElementById('mapCanvas');
		context = canvas.getContext('2d');
		image = new Image();
		image.src = 'http://sstatic.naver.net/keypage/lifesrch/worldmap/img2/img_worldmap7.png';
		context.clearRect(0, 0, canvas.width, canvas.height);
		context.drawImage(image, 0, 0, canvas.width, canvas.height);
		
		console.log(canvas);
		console.log(context);
		console.log(image);
		console.log(image.src);
		console.log("111");
	},

    onButtonTap: function(button, e, options) {
        button.hide();

        this.getMainView().animateActiveItem(0, { type: "slide",  direction: "right" });

        this.getTweetList().deselectAll();

    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        this.getMainView().animateActiveItem(1, { type: "fade", direction: "left" });

        this.getBackButton().show();

        this.getTweetPreview().setData(record.data);

    }

});