/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GNApp.controller.Main', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            mainView: '#MainView',
            toolBar: '#TweetToolbar',
            tweetData: '#TweetData',
            backButton: '#Back',
            tweetPreview: '#TweetPreview'
        },

        control: {
            "[action=back]": {
                tap: 'onButtonTap'
            },
            "#TweetData": {
                itemtap: 'onDataItemTap'
            },
            "#TweetPreview": {
            	activeitemchange: 'onCarouselSlide'
            }
        }
    },

    onButtonTap: function(button, e, options) {
    	
    	var toolbar = Ext.ComponentQuery.query('toolbar')[0];
  	  
  	    if(!toolbar.isHidden())
  	 	   toolbar.setHidden(true);
  	    else
  		   toolbar.setHidden(false);
    	
        button.hide();
        
        this.getToolBar().setTitle('Media');
        
        this.getMainView().animateActiveItem(0, { type: "slide",  direction: "right" });

        this.getTweetData().deselectAll();

    },
    // dataview(Thumbnail) image itemtap event
    onDataItemTap: function(dataview, index, target, record, e, options) {
        this.getMainView().animateActiveItem(1, { type: "fade" });
        
        this.getBackButton().show();
        
        /* index to each image */
    	this.getTweetPreview().setActiveItem(index);

        this.getToolBar().setTitle('into_Media'); /* Carousel Title */
    	
    	
    },
    onCarouselSlide: function(carousel, item){
    	var currentindex = carousel.getActiveIndex();
    	
    	this.getToolBar().setActiveItem(currentindex);
    	
    	var toolbar = Ext.ComponentQuery.query('toolbar')[0];

	  	toolbar.setHidden(true);
	  	
    }
});