/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
//////////////////////////////////

var map;
function init() {
	console.log("open");
	
	map = new daum.maps.Map(document.getElementById('map'), {
		center: new daum.maps.LatLng(37.537123, 127.005523)
	});

	var icon = new daum.maps.MarkerImage(
		'resources/flag.png',
		new daum.maps.Size(32, 32),
		new daum.maps.Point(32, 64)
	);
	var marker = new daum.maps.Marker({
		position: new daum.maps.LatLng(37.537123, 127.005523),
		image : icon
	});
	marker.setMap(map);

	var infowindow = new daum.maps.InfoWindow({
		//content: '\074a href="http://m.daum.net" style="margin:1em;line-height:2;text-decoration:none"\076다음커뮤니케이션\074/a\076'
		content: '<b>dfffff</b>'
	});
	
	daum.maps.event.addListener(marker, "click", function() {
		console.log("open");
		infowindow.open(map, marker);
	});
	
	daum.maps.event.addListener(map, "click", function() {
		console.log("close");
		infowindow.close();
	});
	console.log("close");
}







//////////////////////////////////
var canvas;
var context;
var image;
var flag = new Array();

Point = function(x, y){
	this.x = x;
	this.y = y;
};
var overlayPanel;
var points = new Array();
points[0] = new Point(20, 20+47);
//TODO 학교 정보 표시해야되 이거 어떡해 함???
/*
 * 깃발 클릭시 이벤트처리(학교 정보 표시해야되)
 */

/*
function onClickeMap(event) {
	//console.log(event.x+"/"+event.y);	
	
	if( (points[0].x <= event.x && points[0].x+20 >= event.x) &&
		(points[0].y <= event.y &&  points[0].y+20 >= (event.y))
		)
		{
			console.log("equal!!!");
			//overlayPanel.showBy(this);
			overlayPanel.show();
		}
}
*/
/*
 * 해당 좌표에 깃발 출력
 */
/*
function onPutFlag(index, x, y){
	flag[index] = new Image();
	flag[index].src = '/share/resources/flag.png';
	flag[index].onload = function(){
		context.drawImage(flag[index], x, y, 20, 20);
	};
} 
*/
Ext.define('MyApp.controller.MapController', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
        	shareMainView : 'sharemainview',
        	mapArea: 'mappanel #mapArea',
        	inputArea: 'sharepanel #inputArea',
        	flagOverlay: 'aboutschooloverlay'
        },

        control: {
        }        
    },
   
    
    
    launch: function() {
    	
    	document.getElementById('map');
    	
    	init();
    	/*
    	canvas = document.getElementById('mapCanvas');
		context = canvas.getContext('2d');
		image = new Image();
		image.src = 'http://sstatic.naver.net/keypage/lifesrch/worldmap/img2/img_worldmap7.png';
		context.clearRect(0, 0, canvas.width, canvas.height);
		image.onload = function() {
			context.drawImage(image, 0, 0, canvas.width, canvas.height);
			onPutFlag(0, 20, 20);
        };   
        canvas.addEventListener("click", onClickeMap, false);
        overlayPanel = this.getFlagOverlay();
        */
        
        
        //overlayPanel.show();
        //overlayPanel.showBy(this.getMapArea());
	}
    
});